Re added vendor

diff --git a/bin/pre_compile b/bin/pre_compile
--- a/bin/pre_compile
+++ b/bin/pre_compile
@@ -1,45 +1,45 @@
 #!/usr/bin/env bash
-set -eo pipefail
+# set -eo pipefail
 
-NODE_VERSION=0.12.7
-NODE_BASENAME=node-v${NODE_VERSION}-linux-x64
-NODE_ARCHIVE="http://nodejs.org/dist/v${NODE_VERSION}/${NODE_BASENAME}.tar.gz"
+# NODE_VERSION=0.12.7
+# NODE_BASENAME=node-v${NODE_VERSION}-linux-x64
+# NODE_ARCHIVE="http://nodejs.org/dist/v${NODE_VERSION}/${NODE_BASENAME}.tar.gz"
 
-curl -s -L -o tmp-nodejs.tar.gz $NODE_ARCHIVE
-tar -zxvf tmp-nodejs.tar.gz > /dev/null
-rm tmp-nodejs.tar.gz
-# apt-get install nodejs-legacy
+# curl -s -L -o tmp-nodejs.tar.gz $NODE_ARCHIVE
+# tar -zxvf tmp-nodejs.tar.gz > /dev/null
+# rm tmp-nodejs.tar.gz
+# # apt-get install nodejs-legacy
 
-export PATH=$NODE_BASENAME/bin:tmp-nodejs/$PATH
-echo "path" $PATH
-echo "which node" `which node`
+# export PATH=$NODE_BASENAME/bin:tmp-nodejs/$PATH
+# echo "path" $PATH
+# echo "which node" `which node`
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-    Darwin) sed -l "$c";;
-    *)      sed -u "$c";;
-  esac
-}
+# function indent() {
+#   c='s/^/       /'
+#   case $(uname) in
+#     Darwin) sed -l "$c";;
+#     *)      sed -u "$c";;
+#   esac
+# }
 
-function run_npm_install_global() {
-  package="$1"
-  echo "-----> Installing" $package
-  npm install -g $package 2>&1 | indent
+# function run_npm_install_global() {
+#   package="$1"
+#   echo "-----> Installing" $package
+#   npm install -g $package 2>&1 | indent
 
-  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-    echo " !     Failed to install dependencies with npm"
-    exit 1
-  fi
-}
+#   if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+#     echo " !     Failed to install dependencies with npm"
+#     exit 1
+#   fi
+# }
 
-# install dependencies with npm
-echo "-----> Installing dependencies with npm"
-for dependency in $(cat $BUILD_DIR/npm_requirements.txt)
-do
-    run_npm_install_global $dependency
-done
-npm install
-cd semantic
-gulp build
-echo "Dependencies installed" | indent
+# # install dependencies with npm
+# echo "-----> Installing dependencies with npm"
+# for dependency in $(cat $BUILD_DIR/npm_requirements.txt)
+# do
+#     run_npm_install_global $dependency
+# done
+# npm install
+# cd semantic
+# gulp build
+# echo "Dependencies installed" | indent
